### PR TITLE
Add @babel/plugin-transform-runtime

### PR DESCRIPTION
**Pull request by vtaits**
#281

### CODE REVIEW

**Comment by taion** [comment]
do you have numbers on what this does for the bundle size? my impression is that the helpers compress really well, so the net benefit of runtime when we don't need its kind of polyfilling is quite low

**Comment by jquense** [comment]
It should be a clearer win with Babel 7 I think since the runtime doesn't polyfill anything by default anymore. But we should check

**Comment by vtaits** [comment]
I have screens before and after injecting this plugin to my project.

Before:
image

After:
image

But bundle contains also polyfills and used libraries.

If every library will import same helpers from `@babel/runtime` bundle size will more small.

**Comment by vtaits** [comment]
With `react-overlays`: 280K before, 272K after.

**Pull request closed without merging**
