### PR TITLE
Update file whitelist

### PR DESCRIPTION
**Pull request by cesarandreu**

### CODE REVIEW

**Comment by AlexKVal** [comment]
I propose to migrate from `.npmignore` to `package.json` `files` section.

**Comment by mtscout6** [comment]
I agree, managing a whitelist for releases is easier than managing a blacklist.

**Comment by jquense** [comment]
sounds good to me. @cesarandreu you up for making that change?

**Comment by cesarandreu** [comment]
Sure, I'll do that now

**Comment by cesarandreu** [comment]
Just adding lib to files?

**Comment by jquense** [comment]
I think that is all that's needed?

**Comment by mtscout6** [comment]
We should also include the README and LICENSE otherwise they won't be on npm when we release. You can look here for an example: https://github.com/react-bootstrap/react-bootstrap/blob/v0.24.3/package.json#L27-L33

**Pull request merged**
