### PR TITLE
Support cross-axis positioning

### PR DESCRIPTION
**Pull request by devongovett**
This adds support for some additional placement values to allow alignments along the cross-axis other than center. For example, you can set placement to `"bottom right"` to align the overlay to the bottom right instead of the bottom center of a target. The default remains center, so `"bottom"` should behave the same way as it does currently. Also refactors the `calculatePosition` util to be more generic and share more code between the different directions it operates in.

positions

Should fix most of the cases #52 is asking for.

### CODE REVIEW

**Comment by devongovett** [comment]
ping

**Comment by jquense** [comment]
Sorry for let this slip through the cracks! Looks great just haven't had time to review it. @taion you're a bit more familiar with the position code wdt?

**Comment by ks-s-a** [comment]
My PR (https://github.com/react-bootstrap/react-overlays/pull/176) is not needed, if this one will be merged. Please, review it.

**Comment by taion** [comment]
I took a quick stab at integrating Popper, and it was a horrible dead end because of arrow positioning. Oof.

Could we make the placement naming consistent with Popper, though? i.e. `top-start` and `top-end` instead of `-left` and `-right`... opens up a path to move in that direction in the future.

Also FWIW TWBSv4 totally changes how arrows are drawn.

**Comment by devongovett** [comment]
@taion sorry I missed your comment. We could change the naming, but IMO it seems weird that the cross axis names are different than the primary ones (e.g. start vs left).

**Comment by devongovett** [comment]
Just added a commit to fix positioning when the overlay has a margin as well. Should fix #135.

**Comment by qrohlf** [comment]
even if the cross-axis positioning isn't ready to ship yet, I'd love to see 1533b3c7a56279f39cb6bb6bcaf4efcba9ab3448 get merged and released. Happy to spin up a PR with just those changes if needed. #135 is a blocking issue for using react-overlays in my work.

**Comment by taion** [comment]
Given that people are asking, I'm okay with merging this for now. Thanks for your work here.

Could you fix the names to be consistent with what Popper uses, though? I think that might make it slightly easier to migrate in the future.

**Comment by chrisjaure** [comment]
Is this blocked only on the naming?

**Comment by taion** [comment]
No, we're considering using Popper instead.

**Pull request closed without merging**
