### PR TITLE
Use getOffset regardless of element type

### LINKED ISSUE #89: Dom-helper container width should consider scrollbar
Hi, it seems like dom-helper is using `window.innerWidth` to get container width. This causes an incorrect offset computation in `Position` when the scrollbar is active. Are there any workarounds for it?

### PR DESCRIPTION
**Pull request by khankuan**
Fixes #89

### CODE REVIEW

**Comment by khankuan** [comment]
Will this bug be fixed?

**Comment by jquense** [comment]
I don't think its a bug. Body is odd, as is document and window, that's why they are handled specially. bootstrap does the same thing: https://github.com/twbs/bootstrap/blob/v3.3.6/js/tooltip.js#L367

**Comment by khankuan** [comment]
The problem is the separate logic for `BODY` does not consider scrollbar appearing or not :/

**Comment by jquense** [comment]
I'm having a hard time understanding why that would cause an issue, can you put together a fiddle demonstrating the issue?

**Comment by khankuan** [comment]
Nvm, it seems to be fixed in some way as i went back to debug. Thanks.

**Pull request closed without merging**
