### PR TITLE
[added] disabled prop to rootClose

### PR DESCRIPTION
**Pull request by jquense**
Allow the child to remain mounted while conditionally disabling the behavior

### CODE REVIEW

**Comment by taion** [comment]
I meant to ask – do you remember why we (I) did this instead of checking something like `domHelpers.contains(ReactDOM.findDOMNode(this), event.target)` or something?

**Comment by jquense** [comment]
I don't remember hmm...this approach should be more performant, since its not doing a contains, tho contains is super fast actually. I don't know :P

**Comment by taion** [comment]
It'd also skip the bizarre wrapper.

**Comment by jquense** [comment]
probably worth revisiting

**Pull request merged**
