### PR TITLE
Add back noWrap from React-Bootstrap

### PR DESCRIPTION
**Pull request by taion**
Needed to merge https://github.com/react-bootstrap/react-bootstrap/pull/1174.

### CODE REVIEW

**Comment by jquense** [comment]
LGTM

**Comment by taion** [comment]
Are you okay with cutting a 0.4.3 for this? We need to bump the dep version to merge the react-overlays update for React-Bootstrap v0.25.

**Comment by jquense** [comment]
published!

**Comment by taion** [comment]
Even better :D

**Pull request merged**
