### PR TITLE
Support react v0.14.0

### PR DESCRIPTION
**Pull request by cesarandreu**
DO NOT MERGE

Just sending this PR to increase visibility, issue #3

### CODE REVIEW

**Comment by cesarandreu** [comment]
@taion you said this would break context, so it should use `unstable_renderSubtreeIntoContainer`. Is it simply a matter of replacing all instances of `ReactDOM.render` with `ReactDOM.unstable_renderSubtreeIntoContainer`?

**Comment by jquense** [comment]
ya, you should just be able to replace Portal render calls with it

**Comment by jquense** [comment]
and actually, maybe I can make a seperate branch to PR this against, that way we can release a prerelease version for 0.14 support like we did in react-bootstrap.

**Comment by jquense** [comment]
https://github.com/react-bootstrap/react-overlays/tree/react-14

**Comment by cesarandreu** [comment]
Gotcha. Added a new PR.

**Pull request closed without merging**
