### PR TITLE
Upgrade dom-helpers

### PR DESCRIPTION
**Pull request by TrySound**
Ref https://github.com/react-bootstrap/dom-helpers/commit/87e2fe448b5e852574e1ee63bd3f2102b4c65d79

/cc @jquense

### CODE REVIEW

**Comment by taion** [comment]
might want to update RTG first, though, since we're still pulling in dom-helpers via RTG

**Comment by TrySound** [comment]
Done @taion https://github.com/reactjs/react-transition-group/pull/549

**Comment by bpas247** [comment]
hmm, strange that the CI build didn't kick off. Is this branch up to date with the master branch?

**Comment by TrySound** [comment]
Yes, I pulled master before submmitting.

**Comment by bpas247** [comment]
I just ran the build locally, and it seems to be failing on [this test](https://github.com/react-bootstrap/react-overlays/blob/e8debc2e6814397c6bfc26299b2117b3603ca1ef/test/ModalSpec.js#L416-L434) with the following error:
```
Error: Uncaught AssertionError: expected 'focus-container' to include 'modal' (node_modules/chai/chai.js:239)
```

**Comment by TrySound** [comment]
@bpas247 Looks like it was race condition.

**Comment by jquense** [comment]
yeah that happens occasionally when browser windows aren't actively focused

**Comment by bpas247** [comment]
We've changed up the CI configuration since this PR has been opened (see #448 and #439), so we'll probably need to merge the changes from master into this branch to get those required status checks to kick off properly.

@TrySound do you mind doing that? If not, I'd be more than happy to 😃

**Comment by taion** [comment]
I merged this to master. Will merge once CI goes green.

**Comment by taion** [comment]
okay... so the way we have the codecov secret set up means it's not accessible for builds from forks. bleh.

**Comment by bpas247** [comment]
> okay... so the way we have the codecov secret set up means it's not accessible for builds from forks. bleh.

Any easy fix for that?

**Comment by taion** [comment]
I don't see a way in the secret config to expose secrets to builds from forks. We might just have to wait until there's better first-party support here, and just deal with the pain for now. Not a problem in this case anyway because we don't care about coverage diffs for this change.

**Comment by bpas247** [comment]
This seems related to the overall issue of not allowing [token-free uploads for public repos](https://github.com/codecov/codecov-action/issues/11), so hopefully they'll push a fix for it soon.

**Pull request merged**
