### PR TITLE
Use keyCode instead of key

### LINKED ISSUE #210: Not working, close the modal on press escape key in IE11
I doubt this commits  67d06fd92b7ecb29477fd39eea8767ba16242762.
Because KeyboardEvent.key is 'Esc', not 'Escape' in IE11, so you need to look at KeyboardEvent.keyCode.

rbesc

### PR DESCRIPTION
**Pull request by taion**
Fixes #210

Sorry @jeffredodd!

### CODE REVIEW

**Comment by jquense** [comment]
I don't think this fixes it...React normalizes "Esc" -> "Escape" https://github.com/facebook/react/blob/master/src/renderers/dom/shared/utils/getEventKey.js

**Comment by taion** [comment]
It does, but this is the document keydown event, so it's not going through React.

**Comment by jquense** [comment]
ooo

**Comment by jeffredodd** [comment]
Haha @taion I knew something was weird about using `key`! Now we all know! 😄

**Comment by taion** [comment]
It would be the correct thing if it were a React event, I think, since React normalizes `key`, plus `keyCode` is deprecated, but I think this is the best option for handler a browser event for now.

**Pull request merged**
