### PR TITLE
WIP: Test failures with React 16

### PR DESCRIPTION
**Pull request by jochenberger**
Some tests start to fail with React 16.

### CODE REVIEW

**Comment by jochenberger** [comment]
I'll disable the Modal tests, we're addressing that issue in #201.

**Comment by jochenberger** [comment]
I stole the error boundary part from #208. Unfortunately, it doesn't work with React 15 yet. I guess the `unstable_handleError` does not prevent the error from being thrown. Is this even relevant or will you upgrade to 16 anyway?

**Comment by jquense** [comment]
We can just update the dev dep to 16 for this I think. Does the error boundary approach work?

**Comment by taion** [comment]
We'd need to add an assertion on the number of `expect` calls triggered.

That or save off the exception and do the checking outside `render` (does that work given that `render` is potentially async?).

Otherwise those test cases would pass even if the error is not thrown.

**Comment by jochenberger** [comment]
@jquense, unfortunately, it doesn't seem as if the approach works.

**Comment by jquense** [comment]
some more context https://github.com/facebook/react/issues/10474#issuecomment-332823888

**Comment by taion** [comment]
If we're not testing lifecycle handling here, can we just use the SSR API? That still throws normally, right?

**Comment by jochenberger** [comment]
I can't get it to work with React 16. It seems as if `componentDidCatch` is never called. The behavior with `react-dom/server` is basically the same.

**Comment by taion** [comment]
Doesn't it explicitly throw a normal JS exception with `react-dom/server`?

**Comment by jochenberger** [comment]
Closing in favor of #216

**Pull request closed without merging**
