### PR TITLE
Make `target` work like `container`

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by taion** [comment]
Arguably this is breaking but anybody actually reading the `props` in the arguments to the target function is doing something utterly bizarre.

**Comment by jquense** [comment]
i might the one person doing something bizarre, let me confirm there isn't a reasonable use case...

**Comment by taion** [comment]
It seems really weird for a callback to be able to read the props of a different component.

**Comment by jquense** [comment]
LGTM

**Pull request merged**
