### PR TITLE
Modal container position should be fixed

### PR DESCRIPTION
**Pull request by jmera-cc**
This CSS prevents the modal container from scrolling

### Steps to reproduce
1. Navigate to https://react-bootstrap.github.io/react-overlays/#modals on a mobile device
2. Open a modal
3. You should be able to scroll up/down

### CODE REVIEW

**Comment by jmera-cc** [comment]
I'm getting a test failure & can't seem to figure out what's wrong; any help with someone familiar with the codebase would be appreciated.

**Comment by jmera-cc** [comment]
It looks like recent changes have fixed tests that were failing locally (but passing on CI). This branch is up-to-date, everything looks green. Would someone review?

**Comment by jquense** [comment]
Hi, thanks for the PR I'm not sure I understand what this is solving. We already have props for customizing the container styles, and I don't know that this is a good default style

**Comment by jmera-cc** [comment]
Modals are supposed to disable scrolling of the page content while open. I've noticed that on mobile devices this doesn't work as expected. I think this might be related to https://github.com/twbs/bootstrap/issues/7501

**Comment by jmera-cc** [comment]
https://www.dropbox.com/s/1lfvllx37agnyki/react-overlays.mov?dl=0

**Comment by jmera-cc** [comment]
Although this change works on mobile, `position: fixed` has a side effect of scrolling the user to the top of the page which we don't want.

Further reading:
https://github.com/twbs/bootstrap/issues/15852

**Pull request closed without merging**
