### PR TITLE
Support esm with package.json routers

### PR DESCRIPTION
**Pull request by TrySound**
Similar to react-transition-group approach. Also added babel runtime with esm helpers.

Closes https://github.com/react-bootstrap/react-overlays/pull/282

### CODE REVIEW

**Comment by TrySound** [comment]
Looks like lint errors are unrelated.

**Comment by taion** [comment]
On the runtime thing as well, see https://github.com/reactjs/react-transition-group/pull/507. I think it's a bug in the Babel preset.

**Comment by TrySound** [comment]
Runtime is used for both cjs and esm here.

**Comment by jquense** [comment]
lint errors are expected, it's been in a bad state since #288 i've not quite gotten to it yet

**Comment by taion** [comment]
Ah, I see – you're adding the runtime transform here.

**Comment by TrySound** [comment]
@jquense Lint is fixed. Could you merge?

**Pull request merged**
