### PR TITLE
Add RootCloseWrapper's event support to Overlay

### PR DESCRIPTION
**Pull request by guillaume86**
I used the same style to pass the prop this time.

### CODE REVIEW

**Comment by taion** [comment]
This should probably be called `rootCloseEvent`

**Comment by taion** [comment]
ping

**Comment by antzhdanov** [comment]
I can take it, if original author is not available.

**Comment by taion** [comment]
@antzhdanov Go for it. Thanks!

**Comment by guillaume86** [comment]
Thanks I had completely forgot about this

**Comment by antzhdanov** [comment]
Created a new PR for this: https://github.com/react-bootstrap/react-overlays/pull/230.

**Pull request closed without merging**
