### PR TITLE
[fixed] Modal does not fire show callback

### PR DESCRIPTION
**Pull request by nickuraltsev**

### CODE REVIEW

**Comment by jquense** [comment]
Thanks for the PR, its appreciated.

Slight issue, the call to the callback should be in `componentDidMount` to be consistent with how it's fired the rest of the time in `componentDidUpdate` also I am fairly sure that this will cause the callback to be fired twice on normal updates, one in `onShow` and again in `componentDidUpdate`

**Comment by nickuraltsev** [comment]
The callback is called in `Modal#onShow` which, in its turn, is called in `componentDidMount` and `componentDidUpdate`. ModalSpec.js contains two tests that verify that the callback is called exactly once on mount and exactly once on each update:
* Should fire show callback on mount
* Should fire show callback on update

**Comment by sompylasar** [comment]
@jquense @nickuraltsev What blocks this PR from merging? Thanks.

**Comment by jquense** [comment]
The holidays mostly, and that I forgot about this.

**Comment by sompylasar** [comment]
OK, thanks.

**Comment by jquense** [comment]
thansk for the PR!

**Comment by nickuraltsev** [comment]
You are welcome!

**Pull request merged**
