### PR TITLE
Use a function to store the modal node reference

### PR DESCRIPTION
**Pull request by jochenberger**

### CODE REVIEW

**Comment by jochenberger** [comment]
This probably requires a minor version bump.

**Comment by taion** [comment]
code looks fine. @jquense thoughts on versioning strategy here?

**Comment by jquense** [comment]
it'd be a "major" bump to be safe. folks rely on the refs for testing. Need to see if RB would break as well actually

**Comment by taion** [comment]
we're on minor versions :p LGTM

**Comment by jquense** [comment]
hence the scare quotes :P

**Comment by jochenberger** [comment]
If you think that people need access to the `div`, then maybe we should add a `modalRef` prop to the `Modal`.

**Comment by taion** [comment]
did this get pulled in with that other PR?

**Comment by jochenberger** [comment]
Oh, it seems I have accidentally deleted the branch. Will reopen.

**Pull request merged**
