### PR TITLE
fix: pass full popperConfig into dropdown menu

### PR DESCRIPTION
**Pull request by juliusv**
Signed-off-by: Julius Volz <julius.volz@gmail.com>

### CODE REVIEW

**Comment by juliusv** [comment]
The test failure seems unrelated to this PR (`Please provide an upload token from codecov.io with valid arguments`).

**Comment by taion** [comment]
my apologies to both you and @Viktor-the-great – this was resolved in https://github.com/react-bootstrap/react-overlays/pull/750/, but we forgot to merge

**Comment by taion** [comment]
follow that PR – will merge as soon as CI goes green

**Comment by juliusv** [comment]
@taion Ah no worries, thanks! Glad it's fixed (and more extensively).

**Pull request closed without merging**
