### PR TITLE
fix: root-close firing immediately in react 17

### PR DESCRIPTION
**Pull request by jquense**
love getting to used ancient janky DOM APIs. I think this is a nice simple fix

### CODE REVIEW

**Review by kyletsang — APPROVED** [review]
Nice one!

**Comment by jquense** [comment]
@kyletsang do we know what the deal is with the macOS brew failures in CI here?

**Comment by kyletsang** [comment]
I'm not sure.  I've seen this error about a week ago, but thought it resolved itself as subsequent jobs were run successfully.  I'll take a look later when I get some time.

**Comment by kyletsang** [comment]
@jquense, found this upstream issue:  https://github.com/actions/virtual-environments/issues/1811

**Pull request merged**
